Repository stolostron/search-aggregator, pull requests merged in 2021-04, with the labels that each got.

#120 Delete Dockerfile.prow and rebuild docker image with latest security updates
  Dockerfile.prow
Labels: approved, lgtm

#118 Remove sonar and publish jobs from project
  .travis.yml
  Makefile.prow
Labels: DO NOT MERGE, approved, lgtm

#121 Redis connection timeout
  pkg/dbconnector/pool.go
Labels: approved, lgtm

#122 Update version, OWNERS, and base docker image
  COMPONENT_VERSION
  Dockerfile
  OWNERS
  pkg/config/config.go
Labels: approved, lgtm

#124 disable readiness check
  pkg/handlers/healthProbes.go
  pkg/handlers/healthProbes_test.go
Labels: approved
