Repository stolostron/search-aggregator, pull requests merged in 2021-03, with the labels that each got.

#113 Fix release-ff
  .travis.yml
Labels: approved, lgtm

#114 Prepare repo for prow onboard
  .travis.yml
  DCO
  Dockerfile
  Dockerfile.prow
  Dockerfile.s390x
  Makefile
  Makefile.prow
  go.mod
  go.sum
Labels: approved, lgtm

#115 [release-2.2] update golang.org/x/text version
  go.mod
  go.sum
Labels: lgtm, ok-to-test

#116 [release 2.1] update golang.org/x/text version
  go.mod
  go.sum
Labels: lgtm
